### PR TITLE
pwf: Remove elmyra stub

### PR DESCRIPTION
**Pull request by asriadirahim**
* Elmyra from Google causes the OS to become corrupted on legacy devices such as the Pixel 2 series and prevents the OS from loading properly, we can use from LineageOS as an alternative
* And who really needs to squish their device for Google Assistant

Log: https://katb.in/emafuyireqi
Test: Build & Boot

### CODE REVIEW

**Comment by 306bobby-android** [comment]
Don't use the feature on 5 series

**Comment by asriadirahim** [comment]
> Don't use the feature on 5 series

Also affect for 5 series?

**Comment by 306bobby-android** [comment]
Nope, boots and runs fine here. No issues on Cr 10.6

**Comment by dominator-prime** [comment]
Pixel 7 device fine here 
@ionutgherman can cnf he  knows better he owns pixel 2  also  if I'm correct

**Comment by asriadirahim** [comment]
> Pixel 7 device fine here @ionutgherman can cnf he knows better he owns pixel 2 also if I'm correct

Yeah, i know him, well its look like just affect for pixel legacy, maybe 3 series above...maybe...i will close the pr if Elmyra is importand for u guyss

**Comment by iogh07** [comment]
> > Pixel 7 device fine here @ionutgherman can cnf he knows better he owns pixel 2 also if I'm correct
> 
> Yeah, i know him, well its look like just affect for pixel legacy, maybe 3 series above...maybe...i will close the pr if Elmyra is importand for u guyss

Let me test and will come back with a reply. No need to close PR yet

**Pull request closed without merging**
